In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
dataSet = pd.read_csv("car_evaluation.csv")
dataSet.head(5)

  buying  maint doors persons lug_boot safety Class_Values
0  vhigh  vhigh     2       2    small    low        unacc
1  vhigh  vhigh     2       2    small    med        unacc
2  vhigh  vhigh     2       2    small   high        unacc
3  vhigh  vhigh     2       2      med    low        unacc
4  vhigh  vhigh     2       2      med    med        unacc

In [10]:
IndependentV = dataSet.drop(columns=["Class_Values"])
dependentV = dataSet["Class_Values"]

     buying  maint  doors persons lug_boot safety
0     vhigh  vhigh      2       2    small    low
1     vhigh  vhigh      2       2    small    med
2     vhigh  vhigh      2       2    small   high
3     vhigh  vhigh      2       2      med    low
4     vhigh  vhigh      2       2      med    med
...     ...    ...    ...     ...      ...    ...
1723    low    low  5more    more      med    med
1724    low    low  5more    more      med   high
1725    low    low  5more    more      big    low
1726    low    low  5more    more      big    med
1727    low    low  5more    more      big   high

[1728 rows x 6 columns]

In [11]:
from sklearn.preprocessing import OrdinalEncoder

# categories
buying_price_category = ['low', 'med', 'high', 'vhigh']
maint_cost_category = ['low', 'med', 'high', 'vhigh']
doors_category = ['2', '3', '4', '5more']
person_capacity_category = ['2', '4', 'more']
lug_boot_category = ['small', 'med', 'big']
safety_category = ['low', 'med', 'high']

all_categories = [buying_price_category, maint_cost_category,doors_category,person_capacity_category,lug_boot_category,safety_category]

OE_encoder = OrdinalEncoder(categories= all_categories)
IndependentV = OE_encoder.fit_transform(IndependentV)
IndependentV

array([[3., 3., 0., 0., 0., 0.],
       [3., 3., 0., 0., 0., 1.],
       [3., 3., 0., 0., 0., 2.],
       ...,
       [0., 0., 3., 2., 2., 0.],
       [0., 0., 3., 2., 2., 1.],
       [0., 0., 3., 2., 2., 2.]])

In [12]:
from sklearn.model_selection import train_test_split
IndependentV_train, IndependentV_test, dependentV_train, dependentV_test = train_test_split(IndependentV, dependentV, test_size=0.2, random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# from sklearn import tree
# fig = plt.figure(figsize=(15, 15))
# tree_plot = tree.plot_tree(model, feature_names=['Age', 'EstimatedSalary', 'Purchased'],
#                             class_names=["non Purchased", "Purchased"], filled=True)